import { Outfit } from "next/font/google";
import "./globals.css";
import PageFrame from "./components/pageFrame";
import { Providers } from "./providers";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased text-black`}
      >
        <Providers>
          <PageFrame children={children} />
        </Providers>
      </body>
    </html>
  );
}
